namespace DicomDataGenerator.Services
{
    /// <summary>
    /// DICOM "Body Part Examined" (0018,0015) Defined Terms, per PS3.16 Annex L
    /// (https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_l.html).
    /// </summary>
    public static class BodyPartCatalog
    {
        public static readonly string[] All =
        {
            "ABDOMEN", "ABDOMENPELVIS", "ABDOMINALAORTA", "ACJOINT", "ADRENAL", "AMNIOTICFLUID", "ANKLE",
            "ANTECUBITALV", "ANTCARDIACV", "ACA", "ANTCOMMA", "ANTSPINALA", "ANTTIBIALA", "ANUS",
            "ANUSRECTUMSIGMD", "AORTA", "AORTICARCH", "APPENDIX", "ARTERY", "ASCAORTA", "ASCENDINGCOLON",
            "AXILLA", "AXILLARYA", "AXILLARYV", "AZYGOSVEIN", "BACK", "BASILARA", "BILEDUCT", "BILIARYTRACT",
            "BLADDER", "BLADDERURETHRA", "BRAIN", "BREAST", "BRONCHUS", "BUTTOCK", "CALCANEUS", "CALF",
            "CARDIOVASCSYS", "CAROTID", "BULB", "CELIACA", "CEPHALICV", "CEREBELLUM", "CEREBRALA",
            "CEREBHEMISPHERE", "CSPINE", "CTSPINE", "CERVIX", "CHEEK", "CHEST", "CHESTABDPELVIS",
            "CHESTABDOMEN", "CHOROIDPLEXUS", "CIRCLEOFWILLIS", "CLAVICLE", "COCCYX", "COLON", "COMMONBILEDUCT",
            "CCA", "CFA", "CFV", "COMILIACA", "COMILIACV", "CORONARYARTERY", "CORONARYSINUS", "DESCAORTA",
            "DESCENDINGCOLON", "DUODENUM", "EAR", "ELBOW", "ENDOARTERIAL", "ENDOCARDIAC", "ENDOESOPHAGEAL",
            "ENDOMETRIUM", "ENDONASAL", "ENDONASOPHARYNYX", "ENDORECTAL", "ENDORENAL", "ENDOURETERIC",
            "ENDOURETHRAL", "ENDOVAGINAL", "ENDOVASCULAR", "ENDOVENOUS", "ENDOVESICAL", "WHOLEBODY",
            "EPIDIDYMIS", "EPIGASTRIC", "ESOPHAGUS", "EAC", "ECA", "EXTILIACA", "EXTILIACV", "EXTJUGV",
            "EXTREMITY", "EYE", "EYELID", "FACE", "FACIALA", "FEMORALA", "FEMORALV", "FEMUR", "FETALARM",
            "FETALDIGIT", "FETALHEART", "FETALLEG", "FETALPOLE", "FIBULA", "FINGER", "FLANK", "FONTANEL",
            "FOOT", "FOREARM", "4THVENTRICLE", "GALLBLADDER", "GASTRICV", "GENICULARA", "GESTSAC", "GLUTEAL",
            "GSV", "HAND", "HEAD", "HEADNECK", "HEART", "HEPATICA", "HEPATICV", "HIP", "HUMERUS", "HYPOGASTRIC",
            "HYPOPHARYNX", "ILEUM", "ILIACA", "ILIACV", "ILIUM", "INFMESA", "INFVENACAVA", "INGUINAL",
            "INNOMINATEA", "INNOMINATEV", "IAC", "ICA", "INTILIACA", "INTJUGULARV", "INTMAMMARYA",
            "INTRACRANIAL", "JAW", "JEJUNUM", "JOINT", "KIDNEY", "KNEE", "LACRIMALA", "LARGEINTESTINE",
            "LARYNX", "LATVENTRICLE", "LATRIUM", "LFEMORALA", "LHEPATICV", "LHYPOCHONDRIAC", "LINGUINAL",
            "LLQ", "LLUMBAR", "LPORTALV", "LPULMONARYA", "LUQ", "LVENTRICLE", "LINGUALA", "LIVER", "LOWERLEG",
            "LOWERLIMB", "LOWERTRUNK", "LUMBARA", "LUMBAR", "LSPINE", "LSSPINE", "LUMEN", "LUNG", "MANDIBLE",
            "MASTOID", "MAXILLA", "MEDIASTINUM", "MESENTRICA", "MESENTRICV", "MCA", "MIDHEPATICV",
            "MORISONSPOUCH", "MOUTH", "NASOPHARYNX", "NECK", "NECKCHESTABDPELV", "NECKCHESTABDOMEN",
            "NECKCHEST", "NOSE", "OCCPITALA", "OCCIPTALV", "OPHTHALMICA", "OPTICCANAL", "ORBIT", "OVARY",
            "PANCREAS", "PANCREATICDUCT", "PANCBILEDUCT", "SINUS", "PARASTERNAL", "PARATHYROID", "PAROTID",
            "PATELLA", "PELVIS", "PELVISLOWEXTREMT", "PENILEA", "PENIS", "PERINEUM", "PERONEALA", "PHANTOM",
            "PHARYNX", "PHARYNXLARYNX", "PLACENTA", "POPLITEALA", "POPLITEALFOSSA", "POPLITEALV", "PORTALV",
            "PCA", "POSCOMMA", "POSTIBIALA", "PROFFEMA", "PROFFEMV", "PROSTATE", "PULMONARYA", "PULMONARYV",
            "RADIALA", "RADIUS", "RADIUSULNA", "CULDESAC", "RECTUM", "RENALA", "RENALV", "RETROPERITONEUM",
            "RIB", "RATRIUM", "RFEMORALA", "RHEPATICV", "RHYPOCHONDRIAC", "RINGUINAL", "RLQ", "RLUMBAR",
            "RPORTALV", "RPULMONARYA", "RUQ", "RVENTRICLE", "SIJOINT", "SSPINE", "SFJ", "SAPHENOUSV", "SCALP",
            "SCAPULA", "SCLERA", "SCROTUM", "SELLA", "SEMVESICLE", "SESAMOID", "SHOULDER", "SIGMOID", "SKULL",
            "SMALLINTESTINE", "SPINALCORD", "SPINE", "SPLEEN", "SPLENICA", "SPLENICV", "SCJOINT", "STERNUM",
            "STOMACH", "SUBCLAVIANA", "SUBCLAVIANV", "SUBCOSTAL", "SUBMANDIBULAR", "SUBXIPHOID", "SFA", "SFV",
            "LSUPPULMONARYV", "SMA", "RSUPPULMONARYV", "SUPTHYROIDA", "SVC", "SUPRACLAVICULAR", "SUPRAPUBIC",
            "TARSAL", "TMJ", "TESTIS", "THALAMUS", "THIGH", "3RDVENTRICLE", "THORACICAORTA", "TSPINE",
            "TLSPINE", "THORAX", "THUMB", "THYMUS", "THYROID", "TIBIA", "TIBIAFIBULA", "TOE", "TONGUE",
            "TRACHEA", "TRACHEABRONCHUS", "TRANSVERSECOLON", "TRUNK", "ULNA", "ULNARA", "UMBILICALA",
            "UMBILICAL", "UMBILICALV", "UPPERARM", "UPPERLIMB", "UPPERTRUNK", "UPRURINARYTRACT", "URETER",
            "URETHRA", "UTERUS", "VAGINA", "VEIN", "VERTEBRALA", "VULVA", "WRIST", "ZYGOMA"
        };
    }
}
